title: Ben Portz # your name (or website title) here
logo: "/images/Profile.PNG?raw=true" # your photo (or logo) here
description: | # your text below (remove <br> elements if you don't need line breaks)
  Electro-Mechanical Engineer Co-Op | b.portz5555@gmail.com | (217) 280-3732 
  
  <p
  <a Hello, I'm a Electro-Mechanical engineer currently working at Emerson Electric. With three Co-Op/Internship experience and the skills listed below,
  <a I am currently looking for a design engineering position preferably in EV's, HVAC, or the energy sector. 
  </p>
  
  #### Skills:
  
  <p
  <a software
  <a 1
  <a 2
  </p>
  
  <p
  <a Enegineering
  <a 1
  <a 2
  </p>
  
  <p
  <a Programming
  <a 1
  <a 2
  </p>
  
  <a href="https://www.linkedin.com/in/benjamin-portz-ab0175185">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
